[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
launchos_escrow = "5BQeJxss39ftLC9guf5oyde6x6hkCgAwTB3wk6DF1qRc"
launchos_curve = "Ej8XrDazXPSRFebCYhycbV1LZGdLHCFddRufRMqZUXQF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = '~\.config\solana\devnet.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
